import javax.swing.JOptionPane;
public class TelaCadastroGerente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroGerente
     */
    public TelaCadastroGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTcpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTendereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTtel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtlimpar = new javax.swing.JButton();
        jtenviar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTctps = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTagencia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTsetor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTsalario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 234, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 50, 20);

        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });
        jPanel1.add(jTnome);
        jTnome.setBounds(20, 60, 280, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("CPF");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 50, 20);

        jTcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcpfActionPerformed(evt);
            }
        });
        jPanel1.add(jTcpf);
        jTcpf.setBounds(20, 120, 280, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Endereço");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 160, 120, 20);

        jTendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTenderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTendereco);
        jTendereco.setBounds(20, 180, 280, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Financeiro");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 450, 70, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Telefone");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 270, 70, 14);
        jPanel1.add(jTtel);
        jTtel.setBounds(20, 290, 280, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("CTPS");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 490, 60, 20);

        jtlimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtlimpar.setText("Limpar");
        jtlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlimparActionPerformed(evt);
            }
        });
        jPanel1.add(jtlimpar);
        jtlimpar.setBounds(310, 580, 90, 25);

        jtenviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtenviar.setText("Cadastrar");
        jtenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtenviarActionPerformed(evt);
            }
        });
        jPanel1.add(jtenviar);
        jtenviar.setBounds(400, 580, 100, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Contato");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 230, 51, 15);
        jPanel1.add(jTctps);
        jTctps.setBounds(150, 510, 150, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Salario:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 490, 120, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(400, 390, 120, 14);

        jTagencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTagenciaActionPerformed(evt);
            }
        });
        jPanel1.add(jTagencia);
        jTagencia.setBounds(20, 410, 280, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Agencia");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 390, 82, 15);

        jTsetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsetorActionPerformed(evt);
            }
        });
        jPanel1.add(jTsetor);
        jTsetor.setBounds(20, 350, 280, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Setor");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 330, 82, 15);
        jPanel1.add(jTsalario);
        jTsalario.setBounds(20, 510, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsetorActionPerformed

    private void jTagenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTagenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTagenciaActionPerformed

    private void jtenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtenviarActionPerformed
        Gerente g = new Gerente();
        g.setNome(jTnome.getText());
        g.setCpf(jTcpf.getText());
        g.setEndereco(jTendereco.getText());
        
        g.setTelefone(jTtel.getText());
        g.setSetor(jTsetor.getText());
        g.setAgencia(jTagencia.getText());
        
        g.setCtps(jTctps.getText());
        String salario = jTsalario.getText();
        double s = Double.parseDouble(salario);
        g.setSalario(s);
        g.setTelefone(jTtel.getText());
        BaseDadosGerentes.adicionar(g);
        BaseDadosGerentes.cadastra(g,"gerentes.dat");
        JOptionPane.showMessageDialog(this, "Gerente cadastrado!");
        getContentPane().remove(jtenviar);
        TelaCadastroGerente.this.dispose();
        jtenviar = null;
    }//GEN-LAST:event_jtenviarActionPerformed

    private void jtlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlimparActionPerformed
        jTnome.setText("");
        jTcpf.setText("");
        jTctps.setText("");
        jTendereco.setText("");
        jTtel.setText("");
        jTsetor.setText("");
        jTagencia.setText("");
        jTsalario.setText("");
    }//GEN-LAST:event_jtlimparActionPerformed

    private void jTenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTenderecoActionPerformed

    private void jTcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcpfActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTagencia;
    private javax.swing.JTextField jTcpf;
    private javax.swing.JTextField jTctps;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTsalario;
    private javax.swing.JTextField jTsetor;
    private javax.swing.JTextField jTtel;
    private javax.swing.JButton jtenviar;
    private javax.swing.JButton jtlimpar;
    // End of variables declaration//GEN-END:variables
}
