
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lara
 */
public class TelaCriaConta extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCriaConta
     */
    public TelaCriaConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtnome1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtnumconta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jblimpar = new javax.swing.JButton();
        jbcriar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Criar Conta");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome do cliente:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 170, 15);

        jtnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnome1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtnome1);
        jtnome1.setBounds(10, 30, 320, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Número da conta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 150, 15);
        jPanel1.add(jtnumconta);
        jtnumconta.setBounds(10, 100, 320, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID do cliente:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 330, 15);
        jPanel1.add(jtId);
        jtId.setBounds(10, 170, 320, 30);

        jblimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jblimpar.setText("Limpar");
        jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblimparActionPerformed(evt);
            }
        });
        jPanel1.add(jblimpar);
        jblimpar.setBounds(150, 230, 80, 25);

        jbcriar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcriar.setText("Criar");
        jbcriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcriarActionPerformed(evt);
            }
        });
        jPanel1.add(jbcriar);
        jbcriar.setBounds(240, 230, 90, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbcriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcriarActionPerformed
        Conta c = new Conta();
       String nome = jtnome1.getText();
       Cliente c1 = BaseDadosClientes.buscar(nome); // verifica se o cliente esta cadastrado
       if(c1!=null){
           c.setCliente(c1);
           c.setNum_Conta(jtnumconta.getText());
           c.setId_cliente(jtId.getText());
           BaseDadosContas.adicionar(c);
           BaseDadosContas.cadastra(c,"contas.dat");
           JOptionPane.showMessageDialog(this,"Conta criada com sucesso!");
           
       }
       else{
            JOptionPane.showMessageDialog(this,"Erro ao criar conta, tente novamente!");
          
       }
       getContentPane().remove(jbcriar);
       TelaCriaConta.this.dispose();
       jbcriar = null;  
    }//GEN-LAST:event_jbcriarActionPerformed

    private void jblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblimparActionPerformed
        jtnome1.setText("");
        jtnumconta.setText("");
        jtId.setText("");
    }//GEN-LAST:event_jblimparActionPerformed

    private void jtnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnome1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbcriar;
    private javax.swing.JButton jblimpar;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtnome1;
    private javax.swing.JTextField jtnumconta;
    // End of variables declaration//GEN-END:variables
}
